PREFIX mdw: <http://interiot.eu/ont/middleware.owl#>
PREFIX clients: <http://interiot.eu/clients#>
WITH <http://clients>
DELETE {?clientId ?p ?o}
INSERT {
  ?clientId mdw:callbackUrl ?callbackUrl;
      mdw:receivingCapacity ?receivingCapacity;
      mdw:responseDelivery ?responseDelivery;
      mdw:responseFormat ?responseFormat
}
WHERE {
  ?clientId ?p ?o .
}