PREFIX mdw: <http://interiot.eu/ont/middleware.owl#>
PREFIX clients: <http://interiot.eu/clients#>
PREFIX subscriptions: <http://interiot.eu/clients#>
SELECT *
WHERE {
  GRAPH <http://platforms> {
    ?platformId mdw:name ?name;
        mdw:type ?type;
        mdw:baseEndpoint ?baseEndpoint;
        mdw:location ?location;
        mdw:clientId ?clientId;
        mdw:username ?username;
        mdw:encryptedPassword ?encryptedPassword;
        mdw:encryptionAlgorithm ?encryptionAlgorithm
  }
}