PREFIX mdw: <http://interiot.eu/ont/middleware.owl#>
PREFIX clients: <http://interiot.eu/clients#>
SELECT *
WHERE {
  GRAPH <http://platforms> {
    ?platformId mdw:name ?name;
      mdw:type ?type;
      mdw:baseEndpoint ?baseEndpoint;
      mdw:clientId ?clientId.
    OPTIONAL {
      ?platformId mdw:location ?location;
        mdw:username ?username;
        mdw:encryptedPassword ?encryptedPassword;
        mdw:encryptionAlgorithm ?encryptionAlgorithm;
        mdw:downstreamInputAlignmentName ?downstreamInputAlignmentName;
        mdw:downstreamInputAlignmentVersion ?downstreamInputAlignmentVersion;
        mdw:downstreamOutputAlignmentName ?downstreamOutputAlignmentName;
        mdw:downstreamOutputAlignmentVersion ?downstreamOutputAlignmentVersion;
        mdw:upstreamInputAlignmentName ?upstreamInputAlignmentName;
        mdw:upstreamInputAlignmentVersion ?upstreamInputAlignmentVersion;
        mdw:upstreamOutputAlignmentName ?upstreamOutputAlignmentName;
        mdw:upstreamOutputAlignmentVersion ?upstreamOutputAlignmentVersion.
     }
  }
}