PREFIX mdw: <http://interiot.eu/ont/middleware.owl#>
PREFIX clients: <http://interiot.eu/clients#>
PREFIX subscriptions: <http://interiot.eu/clients#>
INSERT DATA {
  GRAPH <http://subscriptions> {
    ?conversationId mdw:clientId ?clientId;
      mdw:deviceId ?deviceId
  }
}