---
# This is  spec for INTER-IOT MW API Module
swagger: "2.0"
info:
  description: INTER-IoT Middleware API Specification
  version: 1.0.0
  title: INTER-IoT-MW-API
host: inter-iot.eu
basePath: /api
schemes:
- http
paths:
  /query: #Implements MW03
    post:
      tags:
      - public
      description: Posts a query to the MW platform.
      operationId: mw-api-query
      consumes:
        - application/json
      produces:
      - application/json
      parameters:
      - name: query
        in: body
        description: Contains the plafrom query and callback for results
        required: true
        schema: 
          $ref: "#/definitions/MWQueryRequest"
      responses:
        202:
          description: Successful response - query created (Accepted)
          examples:
            application/json :
              {
                unique_callback-id : internal-uuid-121231242345,
                status : sent
              }
        400: 
          description: Bad request (syntax error)
        403: 
          description: Forbidden 
  /callback_query: #Implements MW03
    post:
      tags:
      - private
      description: Posts a result to InterIot.
      operationId: mw-api-query-callback
      consumes:
        - application/json
      produces:
      - application/json
      parameters:
      - name: query-result
        in: body
        description: Contains the query result
        required: true
        schema: 
          $ref: "#/definitions/MWQueryResult"
      responses:
        200:
          description: Result sent
        404: 
          description: Bad request (syntax error)

definitions:
  MWQueryRequest: 
    type: object
    properties:
      callback:
        type: string
      query:
        type: string
  MWQueryResult: 
    type: object
    properties:
      result:
        type: string